name: Deploy Flask to RHEL 7.9

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, rhel-79]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: Start Flask app (background)
        run: |
          nohup python app.py > flask.log 2>&1 &
