name: Basic Shell Pipeline on Self-Hosted RHEL 7.9

on:
  push:
    branches: [main]

jobs:
  shell-pipeline:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        run: |
          curl -sL https://rpm.nodesource.com/setup_18.x | sudo bash -
          sudo yum install -y nodejs
          node -v
          npm -v

      - name: Build step (create a file)
        run: |
          echo "Building the project..."
          mkdir -p build
          echo "Build output from RHEL 7.9 runner" > build/output.txt

      - name: Test step (validate the build output)
        run: |
          echo "Running tests..."
          if grep -q "Build output" build/output.txt; then
            echo "Tests passed!"
          else
            echo "Tests failed!"
            exit 1
          fi

      - name: Deploy step (simulate deployment)
        run: |
          echo "Deploying application..."
          echo "Deployment completed on $(date)" > deploy.log
          cat deploy.log
